# CatchAsync
Catch async is a multi-catcher, it can catch synchronous, asynchronous and Promises.

### Installation
You can use any Node package managers, like `npm` and `yarn` to install the module. If you want to download it, and manually implement it into your project you can use `git`.
```sh
# Install with `npm`
npm i -S catchasync.js

# Install with `yarn`
yarn add catchasync.js

# Download source code with `git`
git clone https://github.com/ihack2712/catchasync
```

### About
CatchAsync module can catch all sorts of functions;
* Synchronous Function
* Synchronous Function > Promise
* Asynchronous Function
* Asynchronous Function > Promise

CatchAsync forces any function to act as a promise, and then uses `.then` and `.catch` to check if it fails or if it succeeds.

### Documentation

#### CatchAsync
Catches promises, asynchronous functions and synchronous functions. CatchAsync can be used as a promisify module, because if no callbacks are provided it will return a promise.

###### Params
| Name      | Type     | Optional | Description                                                                           |
| --------- | -------- | -------- | ------------------------------------------------------------------------------------- |
| method    | [function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions) | No       | This is the method to execute and catch.                                              |
| onError   | [function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions) | Yes      | This method will be used as a callback whenever the method throws or reject an error. |
| onSuccess | [function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions) | Yes      | This method will be used as a callback whenever the method resolves or returns.       |

###### Returns
{[Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)?} If no callbacks (onError & onSuccess) are provided then it will return a promise.

### Examples
##### Use CatchAsync as a promisify module
```js
// Import CatchAsync
const Catch = require('catchasync.js');

// Our function
async function sendMessage (msg)
{
  const Handler = await Client.getMessageConnection();
  const Result = await Handler.messageService.send(msg);
  return Result;
}

// Promisify
const sendMessage2 = Catch(sendMessage);

// Execute
sendMessage2("Hello world")
  .then(result => {
    console.log(`Successfully sent that message to ${result.recepient.username}`)
  })
  .catch(error => {
    // Prevent the app from crashing.
    console.log(error.stack)
  });
```


##### Synchronous Function (without Promise)
```js
// Import CatchAsync
const Catch = require('catchasync.js');

// Our function
function sendMessage (msg)
{
  const Handler = Client.sync.getMessageConnection()
  const Result = Handler.sync.messageService.send(msg)
  return Result
}

// Our Error Callback
function onError (err)
{
  // Prevent app from crashing
  console.log(err.stack)
}

// Our Success Callback (Doesn't need to be provided)
function onSuccess (result)
{
  console.log(`Successfully sent that message to ${result.recepient.username}`)
}

// Execute
Catch(sendMessage, onError, onSuccess)("Hello world");
```

##### Synchronous Function (with Promise)
```js
// Import CatchAsync
const Catch = require('catchasync.js');

// Our function
function sendMessage (msg)
{
  return new Promise(async (resolve, reject) => {
    const Handler = await Client.getMessageConnection()
    const Result = await Handler.messageService.send(msg)
    resolve(Result)
  })
}

// Our Error Callback
function onError (err)
{
  // Prevent app from crashing
  console.log(err.stack)
}

// Our Success Callback (Doesn't need to be provided)
function onSuccess (result)
{
  console.log(`Successfully sent that message to ${result.recepient.username}`)
}

// Execute
Catch(sendMessage, onError, onSuccess)("Hello world");
```

##### Asynchronous Function (without Promise)
```js
// Import CatchAsync
const Catch = require('catchasync.js');

// Our function
async function sendMessage (msg)
{
  const Handler = await Client.getMessageConnection()
  const Result = await Handler.messageService.send(msg)
  return Result
}

// Our Error Callback
function onError (err)
{
  // Prevent app from crashing
  console.log(err.stack)
}

// Our Success Callback (Doesn't need to be provided)
function onSuccess (result)
{
  console.log(`Successfully sent that message to ${result.recepient.username}`)
}

// Execute
Catch(sendMessage, onError, onSuccess)("Hello world");
```

##### Asynchronous Function (with Promise)
```js
// Import CatchAsync
const Catch = require('catchasync.js');

// Our function
async function sendMessage (msg)
{
  return new Promise(async (resolve, reject) => {
    const Handler = await Client.getMessageConnection()
    const Result = await Handler.messageService.send(msg)
    resolve(Result)
  })
}

// Our Error Callback
function onError (err)
{
  // Prevent app from crashing
  console.log(err.stack)
}

// Our Success Callback (Doesn't need to be provided)
function onSuccess (result)
{
  console.log(`Successfully sent that message to ${result.recepient.username}`)
}

// Execute
Catch(sendMessage, onError, onSuccess)("Hello world");
```

# License
MIT License

Copyright (c) 2018 Richard Olsen Sandberg <ihack@theteamcoders.com>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.